# Build settings
theme: jekyll-theme-cayman
markdown: kramdown

# Site settings
title: My AI Blog
description: A funny and informative blog about AI
baseurl: "" # Set this to your repository name if your site is in a subdirectory
url: "https://your-username.github.io" # Update with your GitHub Pages URL

# Navigation
navbar_links:
  - title: Home
    url: /
  - title: About
    url: /about

# Social media links
social_links:
  - title: GitHub
    url: https://github.com/your-username
  - title: Twitter
    url: https://twitter.com/your-twitter-handle

# Exclude files and directories from the build
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
