# Build settings
theme: minima


title: GitHub Pages
tagline: Your sidekick in using GitHub Pages and blogs
description: >-
  Learn how to create a site or blog from your GitHub repositories with GitHub
  Pages.
